"""empty message

Revision ID: 4d984fc9282e
Revises: c339fe017d30
Create Date: 2020-04-09 21:11:24.292095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d984fc9282e'
down_revision = 'c339fe017d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_table', sa.Column('size_h', sa.Integer(), nullable=False))
    op.add_column('image_table', sa.Column('size_w', sa.Integer(), nullable=False))
    op.drop_column('image_table', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_table', sa.Column('size', mysql.VARCHAR(length=150), nullable=False))
    op.drop_column('image_table', 'size_w')
    op.drop_column('image_table', 'size_h')
    # ### end Alembic commands ###
