"""empty message

Revision ID: 6f69c81ba36a
Revises: e24cf61ff625
Create Date: 2020-04-07 16:38:04.433253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f69c81ba36a'
down_revision = 'e24cf61ff625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_table', sa.Column('image', sa.LargeBinary(length=10240), nullable=True))
    op.add_column('image_table', sa.Column('img_album', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_table', 'img_album')
    op.drop_column('image_table', 'image')
    # ### end Alembic commands ###
