"""empty message

Revision ID: c1f0b06a5a64
Revises: 6f69c81ba36a
Create Date: 2020-04-07 16:42:12.021662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f0b06a5a64'
down_revision = '6f69c81ba36a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_table', sa.Column('used_article', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_table', 'used_article')
    # ### end Alembic commands ###
