"""empty message

Revision ID: c339fe017d30
Revises: c7afb05fbb1b
Create Date: 2020-04-09 20:43:06.943451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c339fe017d30'
down_revision = 'c7afb05fbb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_table', sa.Column('size', sa.String(length=150), nullable=False))
    op.add_column('image_table', sa.Column('tag', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_table', 'tag')
    op.drop_column('image_table', 'size')
    # ### end Alembic commands ###
