"""empty message

Revision ID: c7afb05fbb1b
Revises: c1f0b06a5a64
Create Date: 2020-04-09 16:38:46.190868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7afb05fbb1b'
down_revision = 'c1f0b06a5a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_table', sa.Column('filepath', sa.String(length=50), nullable=False))
    op.drop_column('image_table', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_table', sa.Column('image', sa.BLOB(), nullable=True))
    op.drop_column('image_table', 'filepath')
    # ### end Alembic commands ###
